### ISSUE TITLE
Add more info about Frameworks

### ISSUE THREAD

**Issue by gabrielizalo** [troxler/awesome-css-frameworks#4]
Hey.. This list is amazing.. Thanks...

I'd like to add more info about each framework, as number of stars, last commit, watchers, forks and issues.
Do you think that I can add this info to your list with shields.io?

Look the idea here: [JavaScript Crypto Libraries](https://github.com/gabrielizalo/JavaScript-Crypto-Libraries)

If you think that it can be valuable just tell me and I will update your list.

Thanks.

**Comment by troxler** [comment]
Hi. Thank you :)

Thanks for the suggestion. I would very much like to add more information about these frameworks. These badges from Shields, however, fail to load regularly because of rate limitations from GitHub. And even if they *do* load, they are pretty slow. The repository you linked takes almost 12 seconds to finish loading on my fiber connection (and some badges still failed to load).

I'm afraid but I'm really not sure whether adding more badges is a good idea.

**Comment by gabrielizalo** [comment]
Oopss... It takes for you so much time...
Well... No luck then.. Because manually update this kind of info (starts, and so on) is not an option.
ok.. Thanks any way!
; )

**Comment by troxler** [comment]
> Because manually update this kind of info (starts, and so on) is not an option.
No definitely not :) Maybe a CI that regularly updates these numbers/dates and pushes them to the repo would be a better solution.
