### ISSUE TITLE
Demo site and Docs site can be the same

### ISSUE THREAD

**Issue by thezoorat** [troxler/awesome-css-frameworks#67]
according to _CONTRIBUTING.md_
```
- [**TODO**](TODO) - TODO.  
  ![](https://img.shields.io/github/stars/TODO/TODO.svg?style=social&label=Star)
  [Demo](TODO),
  [Docs](TODO),
  [Repo](TODO)
  | #TODO
```
this template has been asked to use ^

but for few entries **demo site** and **docs site** can be that same 
for those cases it will be better to use 
```
  [Demo, Docs](TODO),
```
or
```
  [Demo and Docs](TODO),
```

**Comment by troxler** [comment]
Thanks for the suggestion. As this list is about CSS frameworks, almost every project listed has a demo. For many projects, that is the project website itself. Some projects (also) have the documentation directly on the project page.

Currently it is handled with this logic:
* If the project's repository links to another URL, then use it as the main project link. Otherwise use the repository URL.
* If there is a demo URL which is not the main project URL, add it.
* If there is a docs URL which is not the main project URL, add it.
* If the main project link is not the repository, add a repository link. (I'm aware that this is a little inconsistent at the moment)

I'd like to add as few links as possible per project and avoid having mutliple links pointing to the exact same resource. I see an advantage of your suggestion, but it might also lead to inconsistent entries. E.g. what would you do when the main project URL includes the documentation? In the end, it is always about balancing between the template and having useful entries. For example, some entries already have a slightly different structure.

Overall, I'm a little hesitant to implement your suggestion. I don't see it as making things much clearer to the users of this list.

**Comment by thezoorat** [comment]
got it why you dont wanna do that
